// death variable at location variable

flavor_text = {
    "Village" :
        [
            'Burned at the stake',
            'Hung',
            'Killed in a bar fight',
            'Drowned',
            'Kicked repeatedly by school children',
            'Buried alive',
            'Thrown off of a high place',
            'Buried neck deep and smothered with honey',
            'Stabbed, then kicked, then repeatedly beaten with sticks in the groin',
            'Locked in a room with a swarm of pissed off bees',
            'Stoned by the children of the village',
            'Force-fed hot coals',
            'Death by snoo-snoo',
            'Impaled professionally',
            'Crushed by several large bolders',
            'Drawn and quartered',
            'Tared, feathered, and then beaten',
            'Stripped naked, slathered in cows blood, then given a 10 second head start before the hounds were released',
            'Thrown into a pit of poisonous snakes',
            'Thrown into a bear pit',
            'Hung upsidedown',
            'Bukkake\'d by the villiage to death',
            'Beheaded',
            'Poisoned',
            'Forced blood transfusion',
            'Crucified',
            'Given a lethal lapjob',
            'Dissolved in a vat of acid',
            'Organs harvested to pay for new textbooks',
            'Dragged behind a horse',
            'Shipped to leper colony',
            'Left to die in a bear trap',
            'Exposed to a lethal dose of bureaucracy',
            'Given exactly 1,342 paper cuts',
            'Ground into a paste',
            'Talked at by the town gossip until you kill yourself',
            'Had the papal pear shoved up their bum',
            'Buried in a coffin filled with spiders',
            'Shoved into a barrel and floated downriver',
        ],
    "Werewolf" :
        [
            'Mauled at midnight',
            'Throat torn out',
            'ACL torn',
            'Crushed',
            'Torn into several gnawed pieces',
            'Eaten',
            'Eviscerated',
            'Lethally stubbed toe',
            'Head crushed in',
            'Missing your botton half, dragging yourself towards help',
            'Found missing their head',
            'Nothing left but their butt',
            'With a trail of bloody paw prints leading away from your house',
            'Roasted over a spit',
            'Strangled with claw marks',
            'As a feast for carrion birds',
        ],
    "Location" :
        [
            'the Church House',
            'the Town Square',
            'the Library',
            'the Well',
            'the Old Jenkins Place',
            'the Magistrate\'s office',
            'the edge of town',
            'the barn where you lost your virginity',
            'the place where you felt most safe in the world',
            'that place mom said to stay away from',
            'a grassy knoll',
            'a hill down by the river',
            'the dog kennel',
            'the abandoned mill',
            'the spookiest place you can think of',
            'that one place you thought only you knew about',
        ]
}
